# This file is used to define the objects available on your site.

[site]
name = "string"
description = "string"

[about]
content = "markdown"

[contact]
content = "markdown"

[photo]
title = "string"
file = "image"
