#:schema https://raw.githubusercontent.com/jesseditson/archival/refs/heads/main/objects.schema.json
# This file is used to define the objects available on your site.

[app]
name = "string"
author = "string"
logo = "image"
description = "string"
appstore_download_link = "string"
playstore_download_link = "string"
direct_download_link = "string"
country = "string"
legal_email = "string"

[screenshots]
image = "image"
description = "string"
frame = ["iphone-15-portrait","google-pixel-8-rose-portrait"]

[features]
emoji = "string"
icon = "image"
title = "string"
desc = "string"

[support]
email = "string"
chat_link = "string"

[eula]
content = "markdown"

[terms_of_service]
content = "markdown"

[privacy_policy]
content = "markdown"
