quote = "Robin helped me feel seen and heard in a way I never had before."
author = "Jasmine R."

[thumbnail]
sha = "2c3e7e5dc7a50926d3ab98ccd9ccd601f9a83a6635c4f9a6cafb647ef30a7301"
filename = "professional-1-testimonial-avatar-1.jpg"
mime = "image/jpeg"
display_type = "image"