quote = "Iâ€™ve made more progress in six months with Robin than in years of therapy before."
author = "Tracy S."

[thumbnail]
sha = "a6001ca473eb315799e3ec8e0cb2c8ac817fac47ef549ec3609b5663d62a2e95"
filename = "professional-1-testimonial-avatar-6.jpg"
mime = "image/jpeg"
display_type = "image"