quote = "I trust Robin completely. Thereâ€™s a rare safety and honesty in every single session."
author = "Alexander K."

[thumbnail]
sha = "7730a4f2bf36b60a3df5af797826d4b0e75d465e836867873ddd76042159e7b2"
filename = "professional-1-testimonial-avatar-8.jpg"
display_type = "image"
mime = "image/jpeg"
name = "(uploading)"