name = "Mobile App Name"
author = "Your Name"
description = "A short description of your app"
appstore_download_link = "#"
playstore_download_link = "#"
direct_download_link = "#"
country = "United States"
legal_email = "legal@your-app.app"
copyright_year = "2025"

[logo]
display_type = "image"
filename = "hammer-icon.png"
sha = "deea7947247c4c92e7d86cd33e951e9f22d21d8d309a80281f5824461d8906bb"
mime = "image/png"
