description = "A short description of your app"
name = "App Name"
tagline = "Create Amazing Websites"
appstore_download_link = "#"
playstore_download_link = ""
direct_download_link = ""
country = "United States"
legal_email = "legal@your-app.app"
author = "Your Name"
copyright_year = "2025"

[logo]
sha = "deea7947247c4c92e7d86cd33e951e9f22d21d8d309a80281f5824461d8906bb"
filename = "hammer-icon.png"
mime = "image/png"
display_type = "image"
