feat_one_emoji = "ğŸ”"
feat_one_title = "Feature Title"
feat_one_desc = "Easily find and organize your photos in your library. Search and filter. Easily find and organize your photos in your library. Search and filter."

feat_two_emoji = "ğŸœï¸"
feat_two_title = "Feature Title"
feat_two_desc = "Apply stunning filters and effects. Search through our library of presets."

feat_three_emoji = "ğŸš€"
feat_three_title = "Feature Title"
feat_three_desc = "Share your favorite moments instantly. Create smart collections and send to friends and family."

feat_four_emoji = "ğŸ”’"
feat_four_title = "Feature Title"
feat_four_desc = "Create secure collections that only you or invited people can see. All data is encrypted."

feat_five_emoji = "ğŸª‚"
feat_five_title = "Feature Title"
feat_five_desc = "Back up all your photos securely in the cloud."

feat_six_emoji = "ğŸ”§"
feat_six_title = "Feature Title"
feat_six_desc = "Tag friends and family."