first_name = "Robin"
last_name = "Collette"
business_name = "Robin Therapy, LLC"
title = "Licensed Therapist"
location = "Oakland, CA"
about = """
It's nice to meet you. I am a professional therapist in Atlanta, GA. I believe that through doing work together, you can gain the things that you love the most back. You can move from feeling stuck, tired, and confused to feeling free, energized, and hopeful. I love what I do, because I see it work over and over again.

I support my clients by being straightforward and direct, offering encouragement and giving a clear idea of what the next steps are for you to take. Working with OCD is difficult and I bring much needed laughter to sessions.

I teach you how to understand your OCD and anxiety and will fight some of your fears with you, until eventually I can stand aside and cheer you on as you do the work. I'm in the business of empowering you by teaching you the therapy, doing it together, then eventually seeing you do it all on your own.
"""
