primary_color = "#E74C3C"
accent_color = "#FF6B6B"
background_color = "#F5F5F5"
twitter = "https://twitter.com/verge"
instagram = "https://instagram.com/verge"
tiktok = "https://tiktok.com/@verge"
spotify = "https://open.spotify.com/show/verge-podcast"
apple_podcasts = "https://podcasts.apple.com/podcast/verge-podcast"
google_podcasts = "https://podcasts.google.com/feed/verge-podcast"
youtube = "https://youtube.com/c/theverge"
