order = -1
name = "Brandwein's Bagels"
tagline = "The best bagels in DeKalb county!"

[logo_image]
display_type = "image"
filename = "logo.png"
sha = "0123983214089dd5d426ceb84c331e4cb45c9cefd656754c5ba11b02cb23b415"
mime = "image/png"
