order = 2
title = "Studio Sculpture, Study with Figure"

[file]
filename = "28Panero-superJumbo.jpg"
mime = "image/jpeg"
description = "Black and white photograph of a man kneeling beside a large, bulbous abstract sculpture, taken from a low angle."
display_type = "image"
sha = "91e16922ae2970a2ee6c790ff372bc58dc7b7f1f13caf09d62deba62c959c8c6"
name = "Studio Work with Figure"
