name = "Rachel Stewart"
bio = """
Rachel is a culture journalist who brings a unique perspective to tech discussions. 
With a background in media studies, they focus on how technology shapes our social interactions.
"""
twitter = "https://twitter.com/samrivera"
linkedin = ""
instagram = "https://instagram.com/samrivera"
