order = 9
title = "On Creative Work"
excerpt = "The most important thing is the thing you make next."
date = "2024-11-04"
tags = "quotes, creativity"

content = """
> The most important thing is the thing you make next. As soon as one work is done, you move on to the next. You don't pause to wait for approval.
>
> â€” Rick Rubin
"""
