order = 0
description = "A screenshot of an android home screen"

frame = "google-pixel-8-rose-portrait"

[image]
sha = "4df0b3cf8c4abfa7533d381c33b8f522854a3018f2e766ecf47edf709002e6a1"
filename = "android-screenshot.png"
mime = "image/png"
display_type = "image"
