order = 1
description = "A screenshot of an iOS Home Screen"

frame = "iphone-15-portrait"

[image]
sha = "ab319273ee703aec2d09fb51fae047d3919a97d3a22e23dba59db210c162a2fb"
filename = "ios-screenshot.png"
mime = "image/png"
display_type = "image"
