number = 4
title = "Something Interesting"
description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac ultrices odio. 
Join us as we explore some truly fascinating topics that caught our attention this week.
"""
audio_url = "/audio/episode-4.mp3"
duration = "41:22"
publish_date = "2024-12-20"
featured = false
draft = false
tag1 = "music"
tag2 = "news"
host1 = "host-1"
host2 = "host-2"
order = 4
