order = -1
date = 2009-09-08T00:00:00
title = "Life Of Leisure"
description = """
Suspendisse tincidunt nibh sem, sit amet bibendum magna rutrum sit amet. Quisque rhoncus purus sed nulla aliquam, at congue mi iaculis. Fusce vitae aliquam neque. Integer ullamcorper justo sagittis consequat porta. Fusce id iaculis nisi. Vestibulum luctus gravida.
"""

[image]
sha = "931dc6e6643015151dd48df95abd77994a1ac515f604309d8c32e09622fd03bf"
filename = "band-1-life-of-leisure.jpg"
mime = "image/jpeg"
display_type = "image"
